### ISSUE TITLE
Check if branches can be deleted automatically after they are merges

### ISSUE THREAD

**Issue by Createdd** [Keep-Current/web-miner#22]
I think this would be useful @liadmagen . What do you think? 
Can you check that in the repository settings? I think there is a way to do that.

**Comment by liadmagen** [comment]
check this out:
https://github.com/isaacs/github/issues/1121

**Comment by liadmagen** [comment]
Maybe there's a way through the github API and the CI servers.

**Comment by Createdd** [comment]
Ok cool idea! But I am not quite sure if worth the time. I think it's just easier to delete them? 
Feel free to close this issue :)
