### ISSUE TITLE
Update the slack link in the readme file

### ISSUE THREAD

**Issue by Createdd** [Keep-Current/web-miner#26]
The slack invitation link is not working anymore. Update to 
`
https://join.slack.com/t/keep-current/shared_invite/enQtMzY3Mzk1NjE2MzIzLWZlZWFjMDM1YWYxYmI5ZWE4YmZjNWYzMmNjMzlhMDYzOTIxZDViODhmNTMzZDI0NThmZWVlOTRjNjczZGJiOWE
`

**Comment by azeemansar** [comment]
Quick fix, taking a shot at this, PR here - [#28](https://github.com/Keep-Current/web-miner/pull/28)

**Comment by Createdd** [comment]
closed in #28
