### ISSUE TITLE
Fix pipfile to work with python 3.6?

### ISSUE THREAD

**Issue by Createdd** [Keep-Current/web-miner#27]
Shall we change the required python to 3.6?  (Currently the 
I think currently some libraries do not fully support 3.7. 
For example Tensorflow.

**Comment by liadmagen** [comment]
We can make 3.6 the current version, but we should wait a bit until 3.7 is getting more support.

As for 3.5, i guess we can start dropping it, now that even anaconda made it the 'official' version :)
I guess it's not easy to 'detect' the current mainstream python version, we will have to update it every time manually when it becomes the new mainstream.

**Comment by liadmagen** [comment]
Apparently also Heroku don't support yet 3.7...
so we should change it also in the Pipfile
