### ISSUE TITLE
Project fails when deploying to Heroku

### ISSUE THREAD

**Issue by liadmagen** [Keep-Current/web-miner#29]
The master fails deployment to heroku because of the pipfile version:

-----> Python app detected
 !     The latest version of Python 3.6 is python-3.6.6 (you are using python-3.7.0, which is unsupported).
 !     We recommend upgrading by specifying the latest version (python-3.6.6).
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Need to update SQLite3, clearing cache
-----> Installing python-3.7.0
-----> Installing pip
 !     Push rejected, failed to compile Python app.
 !     Push failed

I suggest setting it in the pipfile to 3.6.6 until they add the support to 3.7.0

**Comment by Createdd** [comment]
@liadmagen Can you check if the latest merge fixed this problem?

**Comment by liadmagen** [comment]
I think it's good now.
