### ISSUE TITLE
Fix codecov as it doesn't work

### ISSUE THREAD

**Issue by Createdd** [Keep-Current/web-miner#33]
See badge in Readme: 
![image](https://user-images.githubusercontent.com/22077628/43674711-70864258-97d8-11e8-902e-3399a6a74ffd.png)

**Comment by Createdd** [comment]
@liadmagen

**Comment by Createdd** [comment]
Is still not working. As referenced in #35  - I think there is a problem with GH webhook

**Comment by liadmagen** [comment]
I give up.

Their documentation is horrible, they ignore pull requests, they claim you don't need to do anything and it's integrates 'automagically' while in reality, we're spending hours and days on it.

I'll remove their shitty product, until they get their shit together.
