### ISSUE TITLE
Improve the clean archtitecture

### ISSUE THREAD

**Issue by Createdd** [Keep-Current/web-miner#39]
I am not quite sure if I have already understood the structure well enough

I think the code base way build upon [this article](http://blog.thedigitalcatonline.com/blog/2016/11/14/clean-architectures-in-python-a-step-by-step-example/) but I think there are some improvements to be made: 

- [x] the `webminer` folder should contain all the app logic. here we created a separate `flask_server` folder. this should be in the webminer folder. the current structure is actually against the clean architecture style
- [x] the naming of the folders and files should be adapted. currently it is way too abstract. this was good for the tutorial in the article, but is not optimal for the project. 

the idea of the clean architecture, is basically to keep modularity and uni-directional dependency. 
![image](https://user-images.githubusercontent.com/22077628/43678376-9721e3ba-9812-11e8-8eb2-eb6b4c408c4a.png)

right now, at least for me, this is not really implemented in a precise way. for example naming of `arxiv_document_use_case.py`

basic articles: 
- https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html
- https://www.codingblocks.net/podcast/clean-architecture-make-your-architecture-scream/

**Comment by liadmagen** [comment]
The basic idea of the clean architecture is to do something like MVC (common for frontend), or CQRS (common for microservices - http://microservices.io/patterns/data/cqrs.html).
In short, logic modules should communicating through another mediator module. 

We should definitely make the project more clear and understandable. A good naming system will also ease the entrance for new-comers.

And on the way, we'll get a deeper understanding of the architecture... :)

**Comment by Createdd** [comment]
https://softwareengineering.stackexchange.com/questions/336677/what-is-the-difference-between-mvp-and-clean-architecture
