### ISSUE TITLE
The file requirements.txt does not contain flask

### ISSUE THREAD

**Issue by usinglight** [Keep-Current/web-miner#55]
**Describe the bug**
The file requirements.txt in root points to requirements/test.txt
There is no item flask in this file.
It is in the pip file, there it is written with capital F Flask
Shouldn't test.txt which is used in the docker file contain flask?

**To Reproduce**
Steps to reproduce the behavior: (for example)

**Expected behavior**
test.txt also contains flask or at least synced with the pip file.

**Screenshots**
not applicable

**Additional context**

**Comment by Createdd** [comment]
The requirements file points to various requirements files. So Flask is actually contained, but still we shouldn't have a Pipfile and requirements.txt file together. 

My suggestion is to remove the requirements.txts'.

What do you think @liadmagen ?

**Comment by elfosardo** [comment]
I've added PR #59 for this

**Comment by Createdd** [comment]
done in #59
